---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-ovs-cni-amd64
  namespace: kube-system
  labels:
    tier: node
    app: ovs-cni
spec:
  template:
    metadata:
      labels:
        tier: node
        app: ovs-cni
    spec:
      serviceAccountName: ovs-cni-marker
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      initContainers:
      - name: ovs-vsctl
        command:
        - /bin/bash
        - -c
        - |
          cp /usr/bin/ovs-vsctl /host/usr/local/bin/_ovs-vsctl
          echo '#!/bin/sh
          _ovs-vsctl --db unix:///run/openvswitch/db.sock $@
          ' > /host/usr/local/bin/ovs-vsctl
          chmod +x /host/usr/local/bin/ovs-vsctl
        image: docker.io/openshift/origin-node:latest
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: localbin
          mountPath: /host/usr/local/bin
      containers:
      - name: plugin
        image: quay.io/kubevirt/ovs-cni-plugin:latest
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cnibin
          mountPath: /host/opt/cni/bin
      - name: marker
        image: quay.io/kubevirt/ovs-cni-marker:latest
        securityContext:
          privileged: true
        args:
          - -node-name
          - $(NODE_NAME)
          - -ovs-socket
          - unix:///host/run/openvswitch/db.sock
        volumeMounts:
          - name: ovs-run
            mountPath: /host/run/openvswitch
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
      volumes:
        - name: localbin
          hostPath:
            path: /usr/local/bin
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
        - name: ovs-run
          hostPath:
            path: /run/openvswitch
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ovs-cni-marker-cr
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/status
  verbs:
  - get
  - update
  - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ovs-cni-marker-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ovs-cni-marker-cr
subjects:
- kind: ServiceAccount
  name: ovs-cni-marker
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ovs-cni-marker
  namespace: kube-system
