apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  generation: 1
  labels:
    machineconfiguration.openshift.io/role: master
  name: 00-master-coredns
spec:
  config:
    ignition:
      version: 2.2.0
    systemd:
      units:
        - contents: |
            [Unit]
            Description=Serve cluster DNS
            Wants=network-online.target
            After=network-online.target
            ConditionPathExists=!/etc/pivot/image-pullspec

            [Service]
            User=root
            WorkingDirectory=/etc/coredns
            ExecStartPre=/usr/local/bin/coredns.sh
            ExecStart=/usr/bin/podman start -a coredns
            ExecStop=/usr/bin/podman stop -t 10 coredns

            Restart=on-failure
            RestartSec=5
            TimeoutStartSec=600

            [Install]
            WantedBy=multi-user.target

          enabled: true
          name: coredns.service
    storage:
      files:
      - contents:
          verification: {}
        filesystem: root
        mode: 0664
        path: /etc/coredns/Corefile
      - contents:
          verification: {}
        filesystem: root
        mode: 0775
        path: /usr/local/bin/coredns.sh
